{
 "title": "Docker Container Monitoring",
 "tags": [
  "eduvault",
  "docker"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Container CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{name!~\"\"}[2m]) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Container Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name!~\"\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Container Network RX",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{name!~\"\"}[2m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Container Network TX",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(container_network_transmit_bytes_total{name!~\"\"}[2m])",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}